%lang starknet

from openzeppelin.token.erc721.enumerable.presets.ERC721EnumerableMintableBurnable import (
    constructor,
    totalSupply,
    tokenByIndex,
    tokenOfOwnerByIndex,
    getApproved,
    isApprovedForAll,
    owner,
    name,
    symbol,
    tokenURI,
    ownerOf,
    setTokenURI,
    balanceOf,
    approve,
    transferOwnership,
    renounceOwnership,
    setApprovalForAll,
    transferFrom,
    safeTransferFrom,
    mint,
    burn,
    supportsInterface,
)